.PHONY: build test doc lint bench
build:
	go build ./...

test:
	go test -race ./...

doc:
	go tool gomarkdoc --exclude-dirs benchmarks ./...

lint:
	go tool golangci-lint run
	go tool govulncheck ./...

bench:
	go test -run=^$$ -bench=. -benchmem ./...
